### PR TITLE
Add OCR_FORCE watcher.py environment variable

### PR DESCRIPTION
**Pull request by pedropombeiro**
This PR adds support for an `OCR_FORCE` environment variable to make watcher.py always trigger OCR for incoming files, allowing overwriting of corrupt text.

### CODE REVIEW

**Comment by MokaMokiMoke** [comment]
How about adding other commonly used parameters e.g. `OPTIMIZE=2` or `LANGUAGE=eng+deu`.
It could make watcher a lot more usefull.

**Comment by jbarlow83** [comment]
Rather than a PR to patch in every one or 40 or so arguments, I'd rather see something that allows configuration. This could be a command line style

```
OCRMYPDF_WATCHER_ARGS="--deskew --force-ocr"
```

(using `ocrmypdf.api.create_options` to convert the string), or maybe JSON...

```
OCRMYPDF_WATCHER_ARGS="{'deskew': true, 'force-ocr': true}"
```

(My hope was people would take watcher.py and customize it to their needs. But it seems users would rather not alter the code.)

Thoughts?

**Comment by pedropombeiro** [comment]
@jbarlow83 It is indeed a much better solution, however my Python skills are not sufficient for me to quickly implement that logic. :-(

**Comment by jbarlow83** [comment]
Added in 54442c9. Went with the JSON string for simplicity. For your case

```
OCR_JSON_SETTINGS='{"force_ocr": true}'
```

**Comment by pedropombeiro** [comment]
> Added in 54442c9. Went with the JSON string for simplicity. For your case
> 
> ```
> OCR_JSON_SETTINGS='{"force_ocr": true}'
> ```

That's awesome @jbarlow83! Thanks for taking the time to implement this important feature! I don't see the commit in the commit list though, can you post a full link to it?

**Pull request closed without merging**
