### PR TITLE
Added Dockerfile for arm32v7 (builds Docker image for Raspberry Pi 3)

### PR DESCRIPTION
**Pull request by wabuMike**
This PR adds a Dockerfile compatible with arm32v7 instruction sets, specifically Raspberry Pi 3.

### CODE REVIEW

**Comment by jbarlow83** [comment]
Thanks for the contribution. Did you build it on Docker Hub? I'd like to see that it builds.

Also, do you know how to set up a test procedure on Docker Hub for it?

**Comment by wabuMike** [comment]
@jbarlow83 No, it's not on Docker Hub yet. I'd love to have it tested somehow. Give me a week or two to find out.

**Comment by mawi12345** [comment]
I would not maintain this as part of this repo (see #426). Maybe we could collect all other "none official / tested" Dockerfiles in a different repo?

**Comment by wabuMike** [comment]
Building images on Docker Hub for architectures different from amd64 and i386 does not work by default. 

Building the proposed Dockerfile can currently only be accomplished on a CPU with arm architecture.

However, there seems to be a way with qemu (see [https://github.com/docker/hub-feedback/issues/1261](https://github.com/docker/hub-feedback/issues/1261)). This will need more investigation on my side.

In the meantime, you might want to consider creating another repo like @mawi12345 suggested.

**Comment by wabuMike** [comment]
I can't find way to autobuild a Dockerfile for arm architecture in Docker Hub. Thus, I will drop this pull request. 

Eventually, I might upload the arm image to my Docker Hub account directly without autobuild.

**Pull request closed without merging**
